"""password_hash

Revision ID: 37bf4e117c4a
Revises: 6e0ab27e3dc8
Create Date: 2020-11-03 11:41:51.903900

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37bf4e117c4a'
down_revision = '6e0ab27e3dc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blood_banks', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('blood_banks', 'password_hash')
    op.add_column('users', sa.Column('password', sa.String(length=128), nullable=False))
    op.drop_column('users', 'password_hash')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('users', 'password')
    op.add_column('blood_banks', sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=False))
    op.drop_column('blood_banks', 'password')
    # ### end Alembic commands ###
