"""blood_bags table

Revision ID: 6e0ab27e3dc8
Revises: 69722baaa4c6
Create Date: 2020-11-02 15:08:11.757244

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects.postgresql import ENUM

# revision identifiers, used by Alembic.
revision = '6e0ab27e3dc8'
down_revision = '69722baaa4c6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blood_bags',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('blood_bank_id', sa.Integer(), nullable=False),
    sa.Column('bag_size_id', sa.Integer(), nullable=False),
    sa.Column('blood_group', ENUM('A_POS', 'A_NEG', 'B_POS', 'B_NEG', 'AB_POS', 'AB_NEG', 'O_POS', 'O_NEG', name='bloodgrouptype', create_type=False), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('collection_date', sa.DateTime(), nullable=False),
    sa.Column('expiry_date', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bag_size_id'], ['bag_sizes.id'], ),
    sa.ForeignKeyConstraint(['blood_bank_id'], ['blood_banks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blood_bags')
    # ### end Alembic commands ###
